version: "3.8"

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"   # Nexus UI
      - "5000:5000"   # Docker repo (hosted)
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

volumes:
  nexus-data: